invoice_list:
    pattern:  /invoice/list
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:index }

invoice_add:
    pattern:  /invoice/add
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:addEditInvoice }

invoice_edit:
    pattern:  /invoice/edit/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:addEditInvoice }

invoice_view:
    pattern:  /invoice/view/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:viewInvoice }

invoice_print:
    pattern:  /invoice/print/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:printInvoice }

invoice_delete:
    pattern:  /invoice/delete/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:deleteInvoice }

invoice_open:
    pattern:  /invoice/open/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:openInvoice }

invoice_close:
    pattern:  /invoice/close/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Invoice:closeInvoice }

quote_list:
    pattern:  /quote/list
    defaults: { _controller: TeclliureInvoiceBundle:Quote:index }

quote_add:
    pattern:  /quote/add
    defaults: { _controller: TeclliureInvoiceBundle:Quote:addEditQuote }

quote_edit:
    pattern:  /quote/edit/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:addEditQuote }

quote_view:
    pattern:  /quote/view/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:viewQuote }

quote_print:
    pattern:  /quote/print/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:printQuote }

quote_delete:
    pattern:  /quote/delete/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:deleteQuote }

quote_open:
    pattern:  /quote/open/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:openQuote }

quote_close:
    pattern:  /quote/close/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:closeQuote }

quote_deny:
    pattern:  /quote/deny/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:denyQuote }

quote_invoice:
    pattern:  /quote/invoice/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:invoiceQuote }

quote_order:
    pattern:  /quote/order/{id}
    defaults: { _controller: TeclliureInvoiceBundle:Quote:orderQuote }

delivery_note_list:
    pattern:  /delivery_note/list
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:index }

delivery_note_add:
    pattern:  /delivery_note/add
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:addEditDeliveryNote }

delivery_note_edit:
    pattern:  /delivery_note/edit/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:addEditDeliveryNote }

delivery_note_view:
    pattern:  /delivery_note/view/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:viewDeliveryNote }

delivery_note_print:
    pattern:  /delivery_note/print/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:printDeliveryNote }

delivery_note_delete:
    pattern:  /delivery_note/delete/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:deleteDeliveryNote }

delivery_note_open:
    pattern:  /delivery_note/open/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:openDeliveryNote }

delivery_note_close:
    pattern:  /delivery_note/close/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:closeDeliveryNote }

delivery_note_deny:
    pattern:  /delivery_note/deny/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:denyDeliveryNote }

delivery_note_invoice:
    pattern:  /delivery_note/invoice/{id}
    defaults: { _controller: TeclliureInvoiceBundle:DeliveryNote:invoiceDeliveryNote }


search_customer:
    pattern: /searchCustomer
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomer }

search_customer_name:
    pattern: /searchCustomerName
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomerName }

update_prices:
    pattern: /updatePrices
    defaults: { _controller: TeclliureInvoiceBundle:Common:updatePrices }

taxes:
    resource: "@TeclliureInvoiceBundle/Controller/TaxController.php"
    type:     annotation